version: 2

sources:
    - name: coingecko
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: coingecko
      tables:
          - name: token_prices
            description: One record per hourly price and token.
    - name: erc20
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: erc20
      tables:
          - name: erc20_transfers
            description: One record per transfer